pipeline {
    agent any

    tools {
        maven "Maven3"
        jdk "Java21"
    }


    environment{
        APP_NAME = "devops-application"
        RELEASE = "1.0.${env.BUILD_NUMBER}"
        DOCKER_USER = "merdo9164"
        DOCKER_PASS = 'TOKEN_ID_DOCKER'
        IMAGE_NAME = "${DOCKER_USER}/${APP_NAME}"
        IMAGE_TAG = "${RELEASE}"


    }

    stages {

        stage ('Clean Workspace'){
            steps {
                cleanWs() // Çalışma alanını temizle
            }
        }

        stage('GitHub') {
            steps {

                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/Merdo9164/Devops.git']])
                echo 'Uygulamayı Github dan çek'

            }
        }

        stage('Test') {
            steps {
                dir('devops_004_pipeline') {
                    script {
                        if (isUnix()) {
                            sh "mvn test"
                        } else {
                            bat "mvn test"
                        }
                    }
                }
            }
        }


        stage('Build Maven') {
            steps {
                echo 'Maven Başlıyor.'
                dir('devops_004_pipeline') {
                    script {
                        if (isUnix()) {
                            sh "mvn clean install"
                            echo 'MacOS ya da Linux'
                        } else {
                            bat "mvn clean install"
                            echo 'Windows'
                        }
                    }
                }
                echo 'Maven bitti.'
            }
        }

        stage('SonarQube') {
                            steps {
                                dir('devops_004_pipeline') {
                                    script {
                                        withSonarQubeEnv(credentialsId: 'TOKEN_ID_SONARQUBE') {
                                            if (isUnix()) {
                                                sh "mvn sonar:sonar"
                                            } else {
                                                bat "mvn sonar:sonar"
                                            }
                                        }
                                    }
                                }
                            }
                        }


        stage('Docker Build Image & DockerHub Push'){
            steps {
                dir('devops_004_pipeline') {

                    script {
                       docker.withRegistry('' , DOCKER_PASS){
                           dockerImage = docker.build "${IMAGE_NAME}"
                           dockerImage.push("${IMAGE_TAG}")
                           dockerImage.push("latest")
                       }
                    }
                }
            }
        }

        stage("Trivy Scan") {
                    steps {
                        script {
                          docker.withRegistry('', DOCKER_PASS) {
                                if (isUnix()) {
                                    sh ('docker run -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy image merdo9164/devops-application:latest --no-progress --scanners vuln  --exit-code 0 --severity HIGH,CRITICAL --format table')
                                } else {
                                    bat ('docker run -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy image merdo9164/devops-application:latest --no-progress --scanners vuln  --exit-code 0 --severity HIGH,CRITICAL --format table')
                                }
                            }
                        }
                    }
        }


        stage('Cleanup Old Docker Images') {
                    steps {
                        script {
                            if (isUnix()) {
                                // Bu repo için tüm image’leri al, tarihe göre sırala, son 3 hariç sil
                                sh """
                                    docker images "${env.IMAGE_NAME}" --format "{{.Repository}}:{{.Tag}} {{.CreatedAt}}" \\
                                    | sort -r -k2 \\
                                    | tail -n +4 \\
                                    | awk '{print \$1}' \\
                                    | xargs -r docker rmi -f
                                """

                            } else {
                                bat """
                                     for /f "skip=3 tokens=1" %%i in ('docker images ${env.IMAGE_NAME} --format "{{.Repository}}:{{.Tag}}" ^| sort') do docker rmi -f %%i
                                """
                            }
                        }
                    }
        }
/*
        stage('Docker Image to DockerHub') {
            steps {
                echo 'Image DockerHuba gönder.'
                   script {
                      withCredentials([string(credentialsId: 'dockerhub', variable: 'dockerhub')]) {
                        // login

                            if (isUnix()) {
                                 sh "docker push merdo9164/devops-application:latest"
                            } else {
                                bat "docker push merdo9164/devops-application:latest"
                            }
                        }

                    }
            }
        }

        stage('Kubernetes(K8s)') {
            steps {
                dir('devops_004_pipeline') {
                    script {
                        kubernetesDeploy (configs: 'deployment-service.yaml', kubeconfigId: 'kubernetes')
                        echo 'K8s içinde image i çalıştır.'
                    }
                }
            }
        }

        stage('Clean') {
            steps {
                 script{
                     if (isUnix()) {
                                 sh "docker image prune -f"
                            } else {
                                bat "docker image prune -f"
                            }
                    }

                echo 'Makinemdeki fazlalık imageleri temizle.'
            }
        }
*/

    }
}